application: ksketchweb
version: 14
runtime: python27
api_version: 1
threadsafe: false

builtins:
#- deferred: on

handlers:
# Uncomment and use this handler for batch updates of entities when necessary
#- url: /update_schema
#  script: update_schema_handler.app  # path to webapp2 application definition.
#  login: admin
#  secure: always

- url: /
  static_files: index.html
  upload: index.html
  
- url: /index.html
  static_files: index.html
  upload: index.html
  
- url: /app
  static_dir: app
  expiration: 1m

- url: /test
  static_dir: test
  expiration: 1m

- url: /user/.*
  script: rpx.application

- url: /.*
  script: handler.application
  
libraries:
- name: webapp2
  version: "2.5.1"


