application: yourAppName
version: yourAppVersion
runtime: python27
api_version: 1
threadsafe: false

includes:
- main.yaml

libraries:
- name: webapp2
  version: "2.5.1"
- name: pycrypto
  version: "2.6"